Custom Blender Template Files
mastodon-sc/mastodon-blender-view pull request #17
Opened 2024-04-18 10:14 UTC by maarzt

There is now a new dialog, that allows the user to specify an empty blender project that will be used when showing the cell tracking data in 3d. A user can save the default template. Make modifications to it, for example: change render settings, add light sources. And then define it to be used a template during executions of "Add Interactive Blender Window" or "Open CSV in Blnder".

![image](https://github.com/mastodon-sc/mastodon-blender-view/assets/24407711/92d09678-0b76-44b6-9bf5-6d87006f5ebd)

![image](https://github.com/mastodon-sc/mastodon-blender-view/assets/24407711/3744dae2-62ac-4969-97f0-f8527db9c70e)

2024-04-18 10:19 UTC, maarzt commented
@stefanhahmann It would be very nice, if you could test this.

2024-04-22 10:20 UTC, stefanhahmann requested changes
Would it be possible to filter for `*.blend` files in the dialog the `browse` in the `Configure Blender Templates` view? If the usual extension for such files is `*.blend`, then I would find this a bit more convenient for users.

![grafik](https://github.com/mastodon-sc/mastodon-blender-view/assets/10515534/66c38f93-002a-4911-b1a1-7684833da0a1)

Beyond that, I was not really able to test this functionality. I saved the default template to a file and set this file to be used as the template in the dialog. Opening Blender still works. Thus, I assume the functionality works as expected. However, I was not able to make any changes to the `*.blend` file, it seems to be a binary format and I do not know how to make changes in it that I would later see.

Would it make sense to provide more than one default Template that user can choose? That would help the users who would like to try different Blender settings but are not able to manipulate the template.blend file theirselves.

2024-04-26 14:33 UTC, maarzt commented on src/main/java/org/mastodon/blender/setup/BlenderSettingsCommand.java
> +	private String INTERACTIVE_DESCRIPTION = "Blender file that is used as empty template for interactive 3D view:";
Hm. I wanted to express that is effectively constant. But yeah changed it

2024-04-26 14:33 UTC, maarzt commented on src/main/java/org/mastodon/blender/setup/BlenderSettingsCommand.java
> +	private String CSV_DESCRIPTION = "Blender file that is used as empty template for CSV Blender view:";
same

2024-04-26 15:36 UTC, maarzt commented on src/main/java/org/mastodon/blender/setup/BlenderSettingsCommand.java
> +		String interactiveTemplate = blenderSettingsService.getInteractiveBlenderTemplate();
done

2024-04-26 15:36 UTC, maarzt commented on src/main/java/org/mastodon/blender/setup/BlenderSettingsCommand.java
> +
done

2024-04-26 15:40 UTC, merged