Add feature color modes
mastodon-sc/mastodon-blender-view pull request #24
Opened 2024-09-09 16:36 UTC by stefanhahmann

Besides TagSets users of the Mastodon Blender View wanted to be able to use Feature Color Modes that can be created in the preferences of Mastodon to color the spots in the Mastodon Blender View.

![grafik](https://github.com/user-attachments/assets/99be0802-23c8-42cf-b543-c858683aa5dc)

This PR adds the possibility to do so. When starting a new `Geometry Nodes Blender Window`, the user can now select tag sets (as was possible already) and valid feature color modes to color the spots in the Blender View:

![grafik](https://github.com/user-attachments/assets/e1fda07d-3277-492f-b1bc-ead0f248f969)

All feature color modes are added as columns to the exported CSV. The selected tag set or feature color is used for coloring the spots in the Blender View:

![GIF 09 09 2024 18-33-16](https://github.com/user-attachments/assets/c797cf66-8ed4-4909-a404-057bcc0faadc)

The feature color modes are also added to the exported CSV in the `Export CSV for Blender` action:

![grafik](https://github.com/user-attachments/assets/84f606a2-8cf6-4e0d-9c09-8bbb63eb2c88)

2024-09-12 15:29 UTC, maarzt requested changes
The complexity of the GraphToCsvUtils class is increased significantly. Which will make it harder to maintain this code and keep it bug free in the future. I think the complexity increase is cause mainly be the complicated API of the ColoringModelMain. I would prefer if there is a SpotColoringModel that wraps around the ProjectModel, and provides an easier API to get SpotColorModes that either refer to a tag or feature.

2024-09-12 15:29 UTC, maarzt commented on src/main/java/org/mastodon/blender/csv/GraphToCsvUtils.java
> +			GraphColorGenerator< Spot, Link > colorGenerator = coloringModel.getFeatureGraphColorGenerator();
These two lines should only be executed once per color mode. But they are called for each spot as well. So they are executed way to often: number of spot * number of feature color modes.

2024-09-12 15:38 UTC, maarzt commented on src/main/java/org/mastodon/blender/csv/ColorSchemeChoice.java
> +					break;
Or use `UIManager.getColor( "ComboBox.background" );` instead.

2024-09-13 14:41 UTC, stefanhahmann commented on src/main/java/org/mastodon/blender/csv/ColorSchemeChoice.java
> +public class ColorSchemeChoice extends JComboBox< String >
> The extends `JComboBox<String>` can be removed, if I'm not mistaken.

Done.

> Maybe rename to `ColorSchemeDialog`

Done.

2024-09-13 14:43 UTC, stefanhahmann commented on src/main/java/org/mastodon/blender/csv/ColorSchemeChoice.java
> +					break;
Done.

The dialog does not rely on the assumption of white background anymore.

![grafik](https://github.com/user-attachments/assets/d3057920-3a9e-448e-9cc8-67e29516cfc4)

2024-09-18 08:38 UTC, stefanhahmann commented on src/main/java/org/mastodon/blender/csv/GraphToCsvUtils.java
> +			GraphColorGenerator< Spot, Link > colorGenerator = coloringModel.getFeatureGraphColorGenerator();
This has been changed. I introduced an interface ColorFunction with implementations for TagSets and FeatureColorModes.
The result of this is that the colorGenerator has to be created only once per color mode.

This brings also the advantage that the tag maps do not have to be carried through to the writeSpots() method.
Another advantage is that tagsets / feature color modes that by chance have the same name as the headlines in the dialog could also be used without causing an exception.

The updated dialog now looks like this:

![grafik](https://github.com/user-attachments/assets/49242f2e-768c-4f11-a2c8-c4f5ba386a9a)

2024-09-18 09:55 UTC, maarzt reviewed
I like it. Only some smaller remarks. Then it can be merged.

2024-09-18 09:55 UTC, maarzt commented on src/test/java/org/mastodon/blender/csv/GraphToCsvUtilsTest.java
>  		Model model = initializeExampleModel();
The test would be cleaner if `initializeExampleModel()` would return the fully setup `ProjectModel`. Renaming the method to `initializeExampleProjectModel()` might make sense too.

2024-09-18 09:55 UTC, maarzt commented on src/main/java/org/mastodon/blender/csv/GraphToCsvUtils.java
> -
Unfortunately the order of input statements was change. I try to be consistent with the order in mastodon core (and other scijava projects, [example](https://github.com/mastodon-sc/mastodon/blob/master/src/main/java/org/mastodon/ui/TagSetMenu.java)). IntelliJ allows to configure the order of imports that it uses.

2024-09-18 09:55 UTC, maarzt commented on src/main/java/org/mastodon/blender/csv/ColorSchemeDialog.java
> +			if ( colorFunction.getGroup() == null )
This condition (`colorFunction.getGroup() == null`) is true only if colorFunction is an EmptyColorFunction. So I would strongly suggest to make this intention explicit be writing:
```suggestion
			if ( colorFunction.getGroup() instanceof EmptyColorFuntion )
```

2024-09-18 09:55 UTC, maarzt commented on src/main/java/org/mastodon/blender/csv/ColorSchemeDialog.java
> +					return new JLabel( colorFunction.toString() );
This line `return new JLabel( colorFunction.toString() );` cause the default entry `[no color scheme]` feel not be highlighted when selected. The situation could be improved by simply removing this line.
```suggestion
					// use default renderer
```

2024-09-18 10:31 UTC, stefanhahmann commented on src/test/java/org/mastodon/blender/csv/GraphToCsvUtilsTest.java
>  		Model model = initializeExampleModel();
Good idea. Changed it.

2024-09-18 10:31 UTC, stefanhahmann commented on src/main/java/org/mastodon/blender/csv/GraphToCsvUtils.java
> -
Good idea. Changed the setting and re-arranged the imports.

2024-09-18 10:31 UTC, stefanhahmann commented on src/main/java/org/mastodon/blender/csv/ColorSchemeDialog.java
> +					return new JLabel( colorFunction.toString() );
Good idea. Changed it.

2024-09-18 10:43 UTC, merged